name: Test Action
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Package action
        run: npm run package

      - name: Test the action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max-reviewers: 2
          threshold: 15
